<?php

namespace ClientBundle\Repository;

/**
 * FacturationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturationRepository extends \Doctrine\ORM\EntityRepository
{
}
