services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    menu.voter.request:
        class: AppBundle\Menu\RequestVoter
        arguments: [ '@request_stack' ]
        tags:
            - { name: knp_menu.voter }

#    app.form.select2:
#        class: Genemu\Bundle\FormBundle\Form\JQuery\Type\Select2Type
#        arguments: [ 'entity' ]
#        tags:
#            - { name: form.type }